# Generated by Django 3.1 on 2020-08-27 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugs',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('IN PROGRESS', 'In Progress'), ('DONE', 'Done'), ('INVALID', 'Invalid')], default='NEW', max_length=12),
        ),
    ]
